base_url = "https://aidoku.app"
title = "Aidoku"
compile_sass = true
build_search_index = false

[markdown]
highlight_code = false
external_links_target_blank = true

[slugify]
paths = "off" # support periods in paths
